import Box from '@mui/material/Box'
import Stack from '@mui/material/Stack'
import Head from 'next/head'
import { useState } from 'react'
import ImageResult from 'components/ImageResult'
import SearchBar from 'components/SearchBar'
import ImageResultData from 'interfaces/ImageResultData'

export default function Home() {
  const [imageResults, setImageResults] = useState<ImageResultData[]>([])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100vh',
          width: '100vw',
          bgcolor: 'green',
        }}
      >
        <SearchBar onResults={setImageResults} />

        <Box
          sx={{
            overflowY: 'auto',
            flexGrow: 1,
            bgcolor: 'red',
            width: '100%',
          }}
        >
          <Stack direction="column">
            {imageResults.map((image) => (
              <ImageResult key={image.id} image={image} />
            ))}
          </Stack>
        </Box>
      </Box>
    </>
  )
}
