import Box from '@mui/material/Box'
import Stack from '@mui/material/Stack'
import TextField from '@mui/material/TextField'
import ImageResult from 'components/ImageResult'
import ImageResultData from 'interfaces/ImageResultData'
import Head from 'next/head'
import { useState } from 'react'
import { queryApi } from 'utils/api'

function Home() {
  const [imageResults, setImageResults] = useState<ImageResultData[]>([])

  async function handleSearch(q: string) {
    const data = await queryApi(q)
    const images = data.hits
    setImageResults(images)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            height: '100vh',
            width: '100vw',
            bgcolor: 'green',
          }}
        >
          <Box
            sx={{
              height: 100,
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <TextField
              id="outlined-basic"
              label="Outlined"
              variant="outlined"
              onChange={(e) => {
                handleSearch(e.target.value)
              }}
            />
          </Box>
          <Box
            sx={{
              overflowY: 'auto',
              flexGrow: 1,
              bgcolor: 'red',
              width: '100%',
            }}
          >
            <Stack direction="column">
              {imageResults.map((image) => (
                <ImageResult key={image.id} image={image} />
              ))}
            </Stack>
          </Box>
        </Box>
      </main>
    </>
  )
}

export default Home
