import Box from '@mui/material/Box'
import Stack from '@mui/material/Stack'
import Head from 'next/head'
import ImageResult from 'features/image-search/ImageResult'
import ImageSearchQueryInput from 'features/image-search/ImageSearchQueryInput'

const imageResults: { id: string; previewURL: string }[] = []
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100vh',
          width: '100vw',
          bgcolor: 'green',
        }}
      >
        <ImageSearchQueryInput />

        <Box
          sx={{
            overflowY: 'auto',
            flexGrow: 1,
            bgcolor: 'red',
            width: '100%',
          }}
        >
          <Stack direction="column">
            {imageResults.map((image) => (
              <ImageResult key={image.id} image={image} />
            ))}
          </Stack>
        </Box>
      </Box>
    </>
  )
}
